openapi: 3.2.0
info:
  title: Splio Customer Platform Export API
  description: API Documentation for Splio Customer Platform
  version: 1.0.0
servers:
- url: https://api.splio.com
- url: http://api.splio.com
tags:
- name: Export
paths:
  /reports/smtprelay/{action_id}/recipients:
    get:
      summary: List recipients of a forward campaign
      description: List recipients of a campaign.
      parameters:
      - name: action_id
        in: path
        required: true
        description: Campaign action's id.
        schema:
          type: string
      - name: per_page
        in: query
        required: false
        description: Number of items displayed per page.
        schema:
          type: integer
          minimum: 1
          maximum: 1000
          default: 20
      - name: page_number
        in: query
        required: false
        description: Page number.
        schema:
          type: integer
          minimum: 1
          default: 1
      responses:
        '200':
          description: Recipients of a smtp relay campaign.
          content:
            application/json:
              examples:
                response:
                  value:
                    count_element: 61
                    current_page: 3
                    per_page: 2
                    elements:
                    - id: 6
                      extid: '6'
                      rcpt: john_smith@mymail.com
                      subject: new products
                      status: done
                      smtpmsg: 250 2.0.0 OK 1456470112 lp7si14301264wjb.73 - gsmtp
                      openings: 2
                      last_open_date: '2018-09-13 09:00:00'
                      clicks: null
                      last_click_date: null
                      unsub: null
                      spam_complaint: null
                      sales_count: null
                      sales_amount: null
                    - id: 7
                      extid: 7ert4
                      rcpt: joe_dalton@softmail.com
                      subject: new products
                      status: hard
                      smtpmsg: '550 Requested action not taken: mailbox unavailable'
                      openings: null
                      last_open_date: null
                      clicks: null
                      last_click_date: null
                      unsub: null
                      spam_complaint: null
                      sales_count: 1
                      sales_amount: 275
        '400':
          description: The request validation failed.
          x-readme: BODYBODY
          content:
            application/json:
              examples:
                response:
                  value:
                    status: 400
                    errors:
                    - error_key: field_1
                      error: wrong_value
                      error_description: The request was malformed and it is unable to be processed. Please review and try again.
        '401':
          description: Authentication failed.
        '403':
          description: Forbidden.
        '404':
          description: Action not found.
          content:
            application/json:
              examples:
                response:
                  value:
                    status: 404
                    errors:
                    - error_key: action_id
                      error: wrong_value
                      error_description: Campaign not found for action_id 50.
      tags:
      - Export
      security:
      - Bearer: []
      operationId: getReportsSmtprelayByActionIdRecipients
      x-operation-id-source: derived
components:
  securitySchemes:
    Bearer:
      description: "For accessing the API a valid JWT token must be passed in all requests in\nthe 'Authorization' header.\n\n\nA valid JWT token is generated by the Authorization API and returned as answer of a call\nto the route /authenticate giving a valid user, password & universe.\n\n\nThe following syntax must be used in the 'Authorization' header :\n\n    Bearer xxxxxx.yyyyyyy.zzzzzz\n"
      type: http
      scheme: bearer
      bearerFormat: JWT
x-origin:
- url: https://api.splio.com/doc.json
  format: swagger
  version: '2.0'
  converter:
    url: https://github.com/mermade/oas-kit
    version: 7.0.8
